export const posts = [
    {
        "postId": 1,
        "userId": 1234,
        "username": "ChennaiRelief",
        "timestamp": "2015-11-17 17:30:00 UTC",
        "location": "Chennai",
        "mediaType": "image",
        "mediaUrl": "https://example.com/image1.jpg",
        "text": "Water levels rising in Kodambakkam. Please help!",
        "hashtags": ["#ChennaiFloods", "#KodambakkamNeedsHelp"],
        "sentiment": "Urgent",
        "urgency": true,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 150,
        "comments": 50,
        "shares": 75
    },
    {
        "postId": 2,
        "userId": 5678,
        "username": "HelpChennai",
        "timestamp": "2015-11-17 18:00:00 UTC",
        "location": "Chennai",
        "mediaType": "video",
        "mediaUrl": "https://example.com/video1.mp4",
        "text": "Rescue operations underway in T Nagar. Please donate to help the victims.",
        "hashtags": ["#ChennaiFloods", "#TNagarRelief"],
        "sentiment": "Hopeful",
        "urgency": false,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 200,
        "comments": 75,
        "shares": 100
    },
    {
        "postId": 3,
        "userId": 9012,
        "username": "ChennaiCitizen",
        "timestamp": "2015-11-17 18:30:00 UTC",
        "location": "Chennai",
        "mediaType": "image",
        "mediaUrl": "https://example.com/image2.jpg",
        "text": "Roads submerged in Adyar. Urgent need for rescue and relief.",
        "hashtags": ["#ChennaiFloods", "#AdyarNeedsHelp"],
        "sentiment": "Desperate",
        "urgency": true,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 120,
        "comments": 40,
        "shares": 60
    },
    {
        "postId": 4,
        "userId": 3456,
        "username": "ChennaiReliefFund",
        "timestamp": "2015-11-17 19:00:00 UTC",
        "location": "Chennai",
        "mediaType": "text",
        "mediaUrl": "",
        "text": "Donate to the Chennai Relief Fund to help those affected by the floods.",
        "hashtags": ["#ChennaiFloods", "#DonateChennai"],
        "sentiment": "Informative",
        "urgency": false,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 50,
        "comments": 20,
        "shares": 30
    },
    {
        "postId": 5,
        "userId": 7890,
        "username": "ChennaiVolunteer",
        "timestamp": "2015-11-17 19:30:00 UTC",
        "location": "Chennai",
        "mediaType": "image",
        "mediaUrl": "https://example.com/image3.jpg",
        "text": "Volunteers distributing food and water in Nungambakkam.",
        "hashtags": ["#ChennaiFloods", "#VolunteerChennai"],
        "sentiment": "Hopeful",
        "urgency": false,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 180,
        "comments": 60,
        "shares": 90
    },
    {
        "postId": 6,
        "userId": 1357,
        "username": "ChennaiResident",
        "timestamp": "2015-11-17 20:00:00 UTC",
        "location": "Chennai",
        "mediaType": "video",
        "mediaUrl": "https://example.com/video2.mp4",
        "text": "Waterlogging in Mylapore. Need urgent help!",
        "hashtags": ["#ChennaiFloods", "#MylaporeNeedsHelp"],
        "sentiment": "Desperate",
        "urgency": true,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 130,
        "comments": 45,
        "shares": 65
    },
    {
        "postId": 7,
        "userId": 2468,
        "username": "ChennaiReliefFund",
        "timestamp": "2015-11-17 20:30:00 UTC",
        "location": "Chennai",
        "mediaType": "text",
        "mediaUrl": "",
        "text": "Your donations are making a difference. Thank you for your support!",
        "hashtags": ["#ChennaiFloods", "#ThankYou"],
        "sentiment": "Grateful",
        "urgency": false,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 60,
        "comments": 25,
        "shares": 35
    },
    {
        "postId": 8,
        "userId": 1023,
        "username": "ChennaiVolunteer",
        "timestamp": "2015-11-17 21:00:00 UTC",
        "location": "Chennai",
        "mediaType": "image",
        "mediaUrl": "https://example.com/image4.jpg",
        "text": "Volunteers distributing relief supplies in Velachery.",
        "hashtags": ["#ChennaiFloods", "#VolunteerChennai"],
        "sentiment": "Hopeful",
        "urgency": false,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 170,
        "comments": 55,
        "shares": 85
    },
    {
        "postId": 9,
        "userId": 4567,
        "username": "ChennaiResident",
        "timestamp": "2015-11-17 21:30:00 UTC",
        "location": "Chennai",
        "mediaType": "video",
        "mediaUrl": "https://example.com/video3.mp4",
        "text": "Waterlogged streets in Tambaram. Urgent need for rescue and relief.",
        "hashtags": ["#ChennaiFloods", "#TambaramNeedsHelp"],
        "sentiment": "Desperate",
        "urgency": true,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 140,
        "comments": 45,
        "shares": 70
    },
    {
        "postId": 10,
        "userId": 8901,
        "username": "ChennaiReliefFund",
        "timestamp": "2015-11-17 22:00:00 UTC",
        "location": "Chennai",
        "mediaType": "text",
        "mediaUrl": "",
        "text": "Your donations are helping us reach more people in need.",
        "hashtags": ["#ChennaiFloods", "#ThankYou"],
        "sentiment": "Grateful",
        "urgency": false,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 70,
        "comments": 30,
        "shares": 40
    },
    {
        "postId": 12,
        "userId": 6789,
        "username": "ChennaiVolunteer",
        "timestamp": "2015-11-17 22:30:00 UTC",
        "location": "Chennai",
        "mediaType": "image",
        "mediaUrl": "https://example.com/image5.jpg",
        "text": "Volunteers distributing blankets and warm clothes in flood-affected areas.",
        "hashtags": ["#ChennaiFloods", "#VolunteerChennai"],
        "sentiment": "Hopeful",
        "urgency": false,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 190,
        "comments": 65,
        "shares": 95
      },
      {
        "postId": 13,
        "userId": 1234,
        "username": "ChennaiRelief",
        "timestamp": "2015-11-18 00:00:00 UTC",
        "location": "Chennai",
        "mediaType": "text",
        "mediaUrl": "",
        "text": "24/7 helpline number for flood relief assistance: 1800-102-1199",
        "hashtags": ["#ChennaiFloods", "#Helpline"],
        "sentiment": "Informative",
        "urgency": false,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 80,
        "comments": 30,
        "shares": 40
      },
      {
        "postId": 14,
        "userId": 5678,
        "username": "HelpChennai",
        "timestamp": "2015-11-18 00:30:00 UTC",
        "location": "Chennai",
        "mediaType": "video",
        "mediaUrl": "https://example.com/video4.mp4",
        "text": "Rescue operations continue in flooded areas. Your support is crucial.",
        "hashtags": ["#ChennaiFloods", "#RescueOperations"],
        "sentiment": "Urgent",
        "urgency": true,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 220,
        "comments": 80,
        "shares": 110
      },
      {
        "postId": 15,
        "userId": 9012,
        "username": "ChennaiCitizen",
        "timestamp": "2015-11-18 01:00:00 UTC",
        "location": "Chennai",
        "mediaType": "image",
        "mediaUrl": "https://example.com/image6.jpg",
        "text": "Water levels rising in Pallavaram. Urgent need for rescue and relief.",
        "hashtags": ["#ChennaiFloods", "#PallavaramNeedsHelp"],
        "sentiment": "Desperate",
        "urgency": true,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 130,
        "comments": 45,
        "shares": 65
      },
      {
        "postId": 16,
        "userId": 3456,
        "username": "ChennaiReliefFund",
        "timestamp": "2015-11-18 01:30:00 UTC",
        "location": "Chennai",
        "mediaType": "text",
        "mediaUrl": "",
        "text": "Your donations are helping us provide food, water, and shelter to the affected families.",
        "hashtags": ["#ChennaiFloods", "#DonateChennai"],
        "sentiment": "Hopeful",
        "urgency": false,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 65,
        "comments": 25,
        "shares": 35
      },
      {
        "postId": 17,
        "userId": 7890,
        "username": "ChennaiVolunteer",
        "timestamp": "2015-11-18 02:00:00 UTC",
        "location": "Chennai",
        "mediaType": "image",
        "mediaUrl": "https://example.com/image7.jpg",
        "text": "Volunteers working tirelessly to provide relief to affected communities.",
        "hashtags": ["#ChennaiFloods", "#VolunteerChennai"],
        "sentiment": "Hopeful",
        "urgency": false,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 195,
        "comments": 70,
        "shares": 105
      },
      {
        "postId": 18,
        "userId": 1357,
        "username": "ChennaiResident",
        "timestamp": "2015-11-18 02:30:00 UTC",
        "location": "Chennai",
        "mediaType": "video",
        "mediaUrl": "https://example.com/video5.mp4",
        "text": "Streets flooded in Chromepet. Urgent need for rescue and relief.",
        "hashtags": ["#ChennaiFloods", "#ChromepetNeedsHelp"],
        "sentiment": "Desperate",
        "urgency": true,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 145,
        "comments": 50,
        "shares": 75
      },
      {
        "postId": 19,
        "userId": 2468,
        "username": "ChennaiReliefFund",
        "timestamp": "2015-11-18 03:00:00 UTC",
        "location": "Chennai",
        "mediaType": "text",
        "mediaUrl": "",
        "text": "Your donations are helping us provide medical aid to the injured.",
        "hashtags": ["#ChennaiFloods", "#DonateChennai"],
        "sentiment": "Hopeful",
        "urgency": false,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 75,
        "comments": 30,
        "shares": 45
      },
      {
        "postId": 20,
        "userId": 1023,
        "username": "ChennaiVolunteer",
        "timestamp": "2015-11-18 03:30:00 UTC",
        "location": "Chennai",
        "mediaType": "image",
        "mediaUrl": "https://example.com/image8.jpg",
        "text": "Volunteers distributing hot meals to affected families in Guindy.",
        "hashtags": ["#ChennaiFloods", "#VolunteerChennai"],
        "sentiment": "Hopeful",
        "urgency": false,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 200,
        "comments": 70,
        "shares": 100
      },
      {
        "postId": 21,
        "userId": 4567,
        "username": "ChennaiResident",
        "timestamp": "2015-11-18 04:00:00 UTC",
        "location": "Chennai",
        "mediaType": "video",
        "mediaUrl": "https://example.com/video6.mp4",
        "text": "Waterlogged streets in Anna Nagar. Urgent need for rescue and relief.",
        "hashtags": ["#ChennaiFloods", "#AnnaNagarNeedsHelp"],
        "sentiment": "Desperate",
        "urgency": true,
        "placeName": "Chennai",
        "coordinates": [13.0827, 80.2707],
        "likes": 150,
        "comments": 50,
        "shares": 75
      }
    ]