export const tweets=[
    {
      "Post ID": 1,
      "Text": "Water levels rising fast in Adyar! Urgently need food and medical aid.",
      "Location": "Adyar",
      "Urgency Level": "Critical",
      "Needs": ["Food", "Medical Aid"],
      "Sentiment": "Desperate",
      "Hashtags": ["#ChennaiFloods", "#HelpChennai", "#FloodRelief"],
      "Date/Time": "2015-11-17 08:30:00 UTC",
      "Geolocation": "Chennai, Adyar",
      "Author Name/Handle": "@help_adayr",
      "Source": "Twitter"
    },
    {
      "Post ID": 2,
      "Text": "Anna Nagar waterlogged, please send rescue teams!",
      "Location": "Anna Nagar",
      "Urgency Level": "Critical",
      "Needs": ["Rescue", "Evacuation"],
      "Sentiment": "Urgent",
      "Hashtags": ["#ChennaiFloods", "#FloodHelp", "#RescueNow"],
      "Date/Time": "2015-11-17 09:00:00 UTC",
      "Geolocation": "Chennai, Anna Nagar",
      "Author Name/Handle": "@RescueChennai",
      "Source": "Twitter"
    },
    {
      "Post ID": 3,
      "Text": "So grateful for the volunteers helping in T Nagar. Shelters are being set up!",
      "Location": "T Nagar",
      "Urgency Level": "Moderate",
      "Needs": ["Shelter", "Volunteers"],
      "Sentiment": "Hopeful",
      "Hashtags": ["#ChennaiFloods", "#ThankYouVolunteers"],
      "Date/Time": "2015-11-17 09:15:00 UTC",
      "Geolocation": "Chennai, T Nagar",
      "Author Name/Handle": "@volunteer_tn",
      "Source": "Facebook"
    },
    {
      "Post ID": 4,
      "Text": "Saidapet is flooded, no food supply. Please help!",
      "Location": "Saidapet",
      "Urgency Level": "Critical",
      "Needs": ["Food", "Medical Aid"],
      "Sentiment": "Desperate",
      "Hashtags": ["#FloodRelief", "#SaveSaidapet"],
      "Date/Time": "2015-11-17 10:00:00 UTC",
      "Geolocation": "Chennai, Saidapet",
      "Author Name/Handle": "@sos_saidapet",
      "Source": "Twitter"
    },
    {
      "Post ID": 5,
      "Text": "Thank you, Chennai! Relief efforts are underway in Villivakkam.",
      "Location": "Villivakkam",
      "Urgency Level": "Low",
      "Needs": ["Volunteers", "Community Support"],
      "Sentiment": "Grateful",
      "Hashtags": ["#ChennaiRelief", "#CommunityHelp"],
      "Date/Time": "2015-11-17 10:30:00 UTC",
      "Geolocation": "Chennai, Villivakkam",
      "Author Name/Handle": "@grateful_villa",
      "Source": "Facebook"
    },
    {
      "Post ID": 6,
      "Text": "Pallavaram under water. Need help with evacuation and medical aid!",
      "Location": "Pallavaram",
      "Urgency Level": "Critical",
      "Needs": ["Evacuation", "Medical Aid"],
      "Sentiment": "Desperate",
      "Hashtags": ["#ChennaiFloods", "#PallavaramRescue"],
      "Date/Time": "2015-11-17 11:00:00 UTC",
      "Geolocation": "Chennai, Pallavaram",
      "Author Name/Handle": "@pallavaramhelp",
      "Source": "Twitter"
    },
    {
      "Post ID": 7,
      "Text": "Residents of Velachery stranded! No food, no electricity. Need immediate help.",
      "Location": "Velachery",
      "Urgency Level": "Critical",
      "Needs": ["Food", "Electricity", "Rescue"],
      "Sentiment": "Urgent",
      "Hashtags": ["#ChennaiFloods", "#VelacheryHelp"],
      "Date/Time": "2015-11-17 11:30:00 UTC",
      "Geolocation": "Chennai, Velachery",
      "Author Name/Handle": "@velacheryrescue",
      "Source": "Twitter"
    },
    {
      "Post ID": 8,
      "Text": "Floods in West Mambalam causing chaos. Need medical supplies urgently.",
      "Location": "West Mambalam",
      "Urgency Level": "Critical",
      "Needs": ["Medical Aid", "Supplies"],
      "Sentiment": "Desperate",
      "Hashtags": ["#ChennaiFloods", "#WestMambalamHelp"],
      "Date/Time": "2015-11-17 12:00:00 UTC",
      "Geolocation": "Chennai, West Mambalam",
      "Author Name/Handle": "@westmambalamhelp",
      "Source": "Twitter"
    },
    {
      "Post ID": 9,
      "Text": "Nungambakkam witnessing heavy rains. Emergency evacuation required immediately!",
      "Location": "Nungambakkam",
      "Urgency Level": "Critical",
      "Needs": ["Evacuation", "Rescue"],
      "Sentiment": "Urgent",
      "Hashtags": ["#ChennaiFloods", "#NungambakkamEvacuation"],
      "Date/Time": "2015-11-17 12:15:00 UTC",
      "Geolocation": "Chennai, Nungambakkam",
      "Author Name/Handle": "@nungambakkamhelp",
      "Source": "Twitter"
    },
    {
      "Post ID": 10,
      "Text": "Sankara Nethralaya providing free medical treatment to flood victims in Chennai.",
      "Location": "Chennai",
      "Urgency Level": "Low",
      "Needs": ["Medical Aid", "Community Support"],
      "Sentiment": "Hopeful",
      "Hashtags": ["#ChennaiFloods", "#SankaraNethralaya"],
      "Date/Time": "2015-11-17 12:30:00 UTC",
      "Geolocation": "Chennai",
      "Author Name/Handle": "@sankaranethralaya",
      "Source": "Facebook"
    }
  ]
  